public enum TokenType {
    COLON, SEMICOLON, DOT, COMMA, EQSIGN, EQUALS, BANG, LPAREN, RPAREN,
    LBRACKET, RBRACKET, LBRACE, RBRACE, AND, OR, LESSTHAN, PLUS,
    MINUS, TIMES, DIV, CLASS, PUBLIC, STATIC, VOID, STRING, EXTENDS,
    INT, BOOLEAN, WHILE, IF, ELSE, MAIN, RETURN, LENGTH, TRUE,
    FALSE, THIS, NEW, PRINTLN, SIDEF, ID, INTLIT, STRINGLIT, EOF
}
